'use client';

import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { api } from '@/lib/api';
import { useI18n } from '@/lib/i18n';
import type { CostEntry, CostReport, RobotSummary, SessionUser } from '@/lib/types';

export function CostTracking({ user,robots }: { user:SessionUser; robots:RobotSummary[] }) {
  const { locale,t,formatDate }=useI18n(); const [days,setDays]=useState(30); const [report,setReport]=useState<CostReport | null>(null); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(false);
  const load=useCallback(async () => { setError(''); try { setReport((await api.costs(days)).data); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Costs could not be loaded'); } },[days]); useEffect(() => { void load(); },[load]);
  const money=(cents:number) => new Intl.NumberFormat(locale === 'de' ? 'de-DE' : 'en-GB',{ style:'currency',currency:report?.currency || 'EUR' }).format(cents/100);
  async function create(event:FormEvent<HTMLFormElement>) { event.preventDefault(); const form=event.currentTarget; const data=new FormData(form); setBusy(true); setError(''); setNotice(''); try { await api.createCost({ robotId:String(data.get('robotId')),category:String(data.get('category')) as CostEntry['category'],description:String(data.get('description')),quantity:Number(data.get('quantity')),unitCostCents:Math.round(Number(data.get('unitCost'))*100),taxRateBasisPoints:Number(data.get('taxRateBasisPoints')),occurredAt:new Date(`${String(data.get('occurredAt'))}T12:00:00`).toISOString(),vendor:String(data.get('vendor')),reference:String(data.get('reference')) }); form.reset(); setNotice(t('Cost entry recorded.')); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Cost entry could not be recorded'); } finally { setBusy(false); } }
  async function voidEntry(entry:CostEntry) { const reason=window.prompt(t('Reason for voiding this cost entry')); if (!reason) return; setBusy(true); setError(''); try { await api.voidCost(entry.id,reason); setNotice(t('Cost entry voided.')); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Cost entry could not be voided'); } finally { setBusy(false); } }
  if (!user.permissions.includes('cost.read')) return null;
  return <section className="panel" aria-labelledby="cost-tracking-title" aria-busy={!report}>
    <div className="panel-title"><div><p className="eyebrow">{t('Financial operations')}</p><h2 id="cost-tracking-title">{t('Cost tracking')}</h2></div><label className="compact-control">{t('Period')}<select value={days} onChange={(event) => setDays(Number(event.target.value))}>{[7,30,90,365].map((value) => <option key={value} value={value}>{value} {t('days')}</option>)}</select></label></div>
    {error && <p className="banner error" role="alert">{error}</p>}<p className="sr-status" aria-live="polite">{notice}</p>
    <div className="metrics analytics-metrics"><article className="metric"><span>{t('Gross costs')}</span><strong>{report ? money(report.totals.grossCents) : '—'}</strong><small>{report?.count || 0} {t('active entries')}</small></article><article className="metric"><span>{t('Net costs')}</span><strong>{report ? money(report.totals.netCents) : '—'}</strong><small>{t('Before tax')}</small></article><article className="metric"><span>{t('Tax')}</span><strong>{report ? money(report.totals.taxCents) : '—'}</strong><small>{report?.voidedCount || 0} {t('voided entries')}</small></article></div>
    {report?.permissions.manage && <><h3>{t('Record cost')}</h3><form className="schedule-form" onSubmit={(event) => void create(event)}><label>{t('Robot')}<select name="robotId" required defaultValue=""><option value="" disabled>{t('Select robot')}</option>{robots.map((robot) => <option key={robot.id} value={robot.id}>{robot.serialNumber}</option>)}</select></label><label>{t('Category')}<select name="category" defaultValue="labor">{['labor','parts','travel','subscription','other'].map((category) => <option key={category} value={category}>{t(category)}</option>)}</select></label><label>{t('Description')}<input name="description" required maxLength={300} /></label><label>{t('Quantity')}<input name="quantity" type="number" min="0.001" max="100000" step="0.001" defaultValue="1" required /></label><label>{t('Unit cost (EUR)')}<input name="unitCost" type="number" min="0" max="1000000" step="0.01" required /></label><label>{t('VAT')}<select name="taxRateBasisPoints" defaultValue="1900"><option value="1900">19%</option><option value="700">7%</option><option value="0">0%</option></select></label><label>{t('Date')}<input name="occurredAt" type="date" max={new Date().toISOString().slice(0,10)} defaultValue={new Date().toISOString().slice(0,10)} required /></label><label>{t('Vendor')}<input name="vendor" maxLength={160} /></label><label>{t('Reference')}<input name="reference" maxLength={120} /></label><button disabled={busy}>{busy ? t('Saving…') : t('Record cost')}</button></form></>}
    <div className="table-scroll" tabIndex={0} role="region" aria-label={t('Cost entries')}><table><caption>{t('Cost entries')}</caption><thead><tr><th scope="col">{t('Date')}</th><th scope="col">{t('Robot')}</th><th scope="col">{t('Category')}</th><th scope="col">{t('Description')}</th><th scope="col">{t('Net')}</th><th scope="col">{t('Tax')}</th><th scope="col">{t('Gross')}</th><th scope="col">{t('Status')}</th><th scope="col">{t('Actions')}</th></tr></thead><tbody>{report?.entries.map((entry) => <tr key={entry.id}><td>{formatDate(entry.occurredAt)}</td><td>{entry.robotSerialNumber}</td><td>{t(entry.category)}</td><td>{entry.description}</td><td>{money(entry.netCents)}</td><td>{money(entry.taxCents)}</td><td>{money(entry.grossCents)}</td><td>{t(entry.status)}</td><td>{report.permissions.manage && entry.status === 'active' ? <button className="quiet" disabled={busy} onClick={() => void voidEntry(entry)}>{t('Void')}</button> : '—'}</td></tr>)}</tbody></table></div>
    {!report?.entries.length && <p className="empty">{t('No costs recorded for this period.')}</p>}<div className="panel-actions"><a className="button-link secondary" href={`/api/v1/costs.csv?days=${days}`}>{t('Export CSV')}</a></div>
  </section>;
}
