'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import type { ComparisonMetrics, FleetComparisonData } from '@/lib/types';

const metrics: Array<{ key: keyof ComparisonMetrics; label: string }> = [{ key: 'events', label: 'Events' }, { key: 'incidents', label: 'Incidents' }, { key: 'casesOpened', label: 'Cases opened' }, { key: 'casesClosed', label: 'Cases closed' }, { key: 'maintenanceCompleted', label: 'Maintenance completed' }];

export function FleetComparison() {
  const [groupBy, setGroupBy] = useState<'site' | 'provider'>('site'); const [days, setDays] = useState(30); const [report, setReport] = useState<FleetComparisonData | null>(null); const [error, setError] = useState('');
  useEffect(() => { let active = true; setError(''); setReport(null); api.fleetComparison(groupBy, days).then(({ data }) => { if (active) setReport(data); }).catch((e: Error) => { if (active) setError(e.message); }); return () => { active = false; }; }, [groupBy, days]);
  return <section className="panel"><h2>Fleet comparison</h2><div className="filters"><label>Compare by<select value={groupBy} onChange={(e) => setGroupBy(e.target.value as 'site' | 'provider')}><option value="site">Site</option><option value="provider">Provider</option></select></label><label>Comparison period<select value={days} onChange={(e) => setDays(Number(e.target.value))}>{[7, 30, 90, 365].map((value) => <option key={value} value={value}>{value} days</option>)}</select></label></div>{error && <p className="error" role="alert">{error}</p>}{!report && !error && <p aria-live="polite">Loading comparison…</p>}{report && <><p>{new Date(report.currentPeriod.from).toLocaleDateString()}–{new Date(report.currentPeriod.to).toLocaleDateString()} versus {new Date(report.previousPeriod.from).toLocaleDateString()}–{new Date(report.previousPeriod.to).toLocaleDateString()}. Fleet and online counts are current snapshots, not historical availability.</p><div className="table-scroll" tabIndex={0} role="region" aria-label="Fleet comparison results"><table><caption>Current / previous totals and absolute change</caption><thead><tr><th scope="col">{groupBy === 'site' ? 'Site' : 'Provider'}</th><th scope="col">Robots / online now</th>{metrics.map((metric) => <th scope="col" key={metric.key}>{metric.label}</th>)}</tr></thead><tbody>{report.data.map((group) => <tr key={group.id}><th scope="row">{group.label}</th><td>{group.robots} / {group.online}</td>{metrics.map(({ key }) => <td key={key}>{group.current[key]} / {group.previous[key]} ({group.change[key] > 0 ? '+' : ''}{group.change[key]})</td>)}</tr>)}</tbody></table></div>{!report.data.length && <p className="empty">No visible fleet to compare.</p>}</>}</section>;
}
