'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { attachmentAccept, readAttachment } from '@/lib/attachments';
import type { RobotSummary, SupportTicket } from '@/lib/types';

export function SupportPortal({ robots, onDataChanged }: { robots: RobotSummary[]; onDataChanged: () => void }) {
  const [tickets, setTickets] = useState<SupportTicket[]>([]); const [selected, setSelected] = useState(''); const [query, setQuery] = useState(''); const [status, setStatus] = useState('');
  const [permissions, setPermissions] = useState({ create: false, reply: false, manage: false }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { const result = await api.tickets(); setTickets(result.data); setPermissions(result.permissions); } catch (e) { setError(e instanceof Error ? e.message : 'Tickets could not be loaded'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]); const ticket = tickets.find((item) => item.id === selected);
  async function submit(event: FormEvent<HTMLFormElement>, reply = false) {
    event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setBusy(true); setError('');
    try { const attachment = await readAttachment(data.get('attachment') as File); const result = reply ? await api.replyTicket(selected, { message: String(data.get('message')), ...(permissions.manage ? { status: String(data.get('status')) } : {}), attachment }) : await api.createTicket({ robotId: String(data.get('robotId')), title: String(data.get('title')), description: String(data.get('description')), category: String(data.get('category')), severity: String(data.get('severity')), attachment }); setSelected(result.data.id); form.reset(); await load(); onDataChanged(); }
    catch (e) { setError(e instanceof Error ? e.message : 'Ticket could not be saved'); } finally { setBusy(false); }
  }
  return <div className="stack">{error && <p className="banner error" role="alert">{error}<button onClick={() => void load()}>Retry</button></p>}
    {permissions.create && <section className="panel"><h2>Create support ticket</h2><form className="schedule-form" onSubmit={(e) => void submit(e)}><label>Support robot<select name="robotId" required defaultValue=""><option value="" disabled>Select robot</option>{robots.map((robot) => <option key={robot.id} value={robot.id}>{robot.serialNumber}</option>)}</select></label><label>Ticket title<input name="title" required maxLength={160} /></label><label>Category<select name="category">{['technical', 'maintenance', 'integration', 'account', 'other'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Ticket priority<select name="severity" defaultValue="warning">{['info', 'warning', 'error', 'critical'].map((item) => <option key={item}>{item}</option>)}</select></label><label className="wide">Issue description<textarea name="description" required maxLength={4000} /></label><label>Ticket attachment (maximum 2 MB)<input name="attachment" type="file" accept={attachmentAccept} /></label><button disabled={busy || !robots.length}>Create ticket</button></form></section>}
    <section className="panel"><h2>Support tickets</h2><div className="filters"><label>Search tickets<input value={query} onChange={(e) => setQuery(e.target.value)} /></label><label>Filter ticket status<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option>{['open', 'in_progress', 'waiting', 'resolved', 'closed'].map((item) => <option key={item}>{item}</option>)}</select></label></div>{loading && <p aria-live="polite">Loading tickets…</p>}<div className="records">{tickets.filter((item) => (!status || item.status === status) && `${item.title} ${item.externalId} ${item.robotSerialNumber}`.toLowerCase().includes(query.toLowerCase())).map((item) => <article key={item.id}><div><strong>{item.title}</strong><small>{item.robotSerialNumber} · {item.status}</small></div><button onClick={() => setSelected(item.id)}>Open ticket {item.externalId}</button></article>)}</div>{!loading && !tickets.length && <p className="empty">No tickets yet.</p>}</section>
    {ticket && <section className="panel"><h2>Conversation · {ticket.title}</h2><p>{ticket.externalId} · {ticket.status}</p>{ticket.messages.map((message) => <article className="evidence" key={message.id}><strong>{message.authorName}</strong><small> · {new Date(message.createdAt).toLocaleString()}</small><p className="message-text">{message.message}</p>{message.attachment && <a href={`/api/v1/support/tickets/${encodeURIComponent(ticket.id)}/messages/${encodeURIComponent(message.id)}/attachment`}>Download {message.attachment.name}</a>}</article>)}{permissions.reply && <form key={ticket.id + ticket.status} className="schedule-form" onSubmit={(e) => void submit(e, true)}><label className="wide">Reply message<textarea name="message" required maxLength={4000} /></label>{permissions.manage && <label>Reply status<select name="status" defaultValue={ticket.status}>{['open', 'in_progress', 'waiting', 'resolved', 'closed'].map((item) => <option key={item}>{item}</option>)}</select></label>}<label>Reply attachment (maximum 2 MB)<input name="attachment" type="file" accept={attachmentAccept} /></label><button disabled={busy}>Send reply</button></form>}</section>}
  </div>;
}
