'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { api } from '@/lib/api';
import type { RobotSummary, SessionUser, WorkforceMatrix, WorkOrder } from '@/lib/types';

export function TechnicianCalendar({ robots, user }: { robots: RobotSummary[]; user: SessionUser }) {
  const [matrix, setMatrix] = useState<WorkforceMatrix | null>(null); const [orders, setOrders] = useState<WorkOrder[]>([]); const [robotId, setRobotId] = useState('');
  const [week, setWeek] = useState(new Date().toISOString().slice(0, 10)); const [technicianId, setTechnicianId] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const [workforce, workOrders] = await Promise.all([api.workforce(), api.workOrders()]); setMatrix(workforce.data); setOrders(workOrders.data); } catch (e) { setError(e instanceof Error ? e.message : 'Calendar could not be loaded'); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(action: () => Promise<unknown>) { setBusy(true); setError(''); try { await action(); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Change could not be saved'); } finally { setBusy(false); } }
  async function schedule(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); await save(async () => { await api.createWorkOrder({ robotId, technicianId: String(data.get('technicianId')), title: String(data.get('title')), description: String(data.get('description')), priority: String(data.get('priority')), startsAt: new Date(String(data.get('startsAt'))).toISOString(), endsAt: new Date(String(data.get('endsAt'))).toISOString() }); form.reset(); setRobotId(''); }); }
  async function qualification(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); await save(async () => { await api.addQualification(technicianId, { kind: String(data.get('kind')), code: String(data.get('code')), issuer: String(data.get('issuer')), validUntil: String(data.get('validUntil')) || undefined }); form.reset(); }); }
  const eligible = matrix?.rows.filter((row) => row.robot.id === robotId && row.eligibility.eligible).map((row) => row.technician.id) || [];
  const days = Array.from({ length: 7 }, (_, offset) => { const date = new Date(`${week}T00:00:00`); date.setDate(date.getDate() + offset); return date; });
  return <div className="stack">{error && <p className="banner error" role="alert">{error}<button onClick={() => void load()}>Retry</button></p>}
    <section className="panel"><div className="panel-title"><h2>Technician calendar</h2><label>Week starting<input type="date" value={week} onChange={(e) => { if (e.target.value) setWeek(e.target.value); }} /></label></div><p>Times use your browser’s local timezone. Qualifications and overlapping bookings are checked before saving.</p><div className="calendar-grid" tabIndex={0} role="region" aria-label="Technician weekly calendar">{days.map((day) => { const next = new Date(day); next.setDate(next.getDate() + 1); return <section key={day.toISOString()}><h3>{day.toLocaleDateString(undefined, { weekday: 'short', day: 'numeric', month: 'short' })}</h3>{orders.filter((order) => new Date(order.startsAt) < next && new Date(order.endsAt) > day && order.status !== 'cancelled').map((order) => <article className="calendar-order" key={order.id}><strong>{order.title}</strong><p>{order.technicianName} · {order.robotSerialNumber}</p><small>{new Date(order.startsAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}–{new Date(order.endsAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} · {order.status}</small>{(user.permissions.includes('work_order.manage') || user.permissions.includes('work_order.update_assigned')) && !['completed', 'cancelled'].includes(order.status) && <form onSubmit={(e) => { e.preventDefault(); const data = new FormData(e.currentTarget); void save(() => api.updateWorkOrder(order.id, String(data.get('status')), String(data.get('completionNote')))); }}><label>Work status<select name="status" defaultValue={order.status}>{['scheduled', 'in_progress', 'blocked', 'completed', 'cancelled'].map((status) => <option key={status}>{status}</option>)}</select></label><label>Completion note<input name="completionNote" maxLength={2000} defaultValue={order.completionNote || ''} /></label><button disabled={busy}>Update work order</button></form>}</article>)}</section>; })}</div>{!matrix && !error && <p aria-live="polite">Loading workforce…</p>}</section>
    {user.permissions.includes('work_order.manage') && matrix && <section className="panel"><h2>Schedule technician visit</h2><form className="schedule-form" onSubmit={schedule}><label>Visit robot<select required value={robotId} onChange={(e) => setRobotId(e.target.value)}><option value="">Select robot</option>{robots.map((robot) => <option key={robot.id} value={robot.id}>{robot.serialNumber}</option>)}</select></label><label>Qualified technician<select key={robotId} name="technicianId" required defaultValue=""><option value="">Select qualified technician</option>{matrix.technicians.filter((technician) => eligible.includes(technician.id) && !['off_duty', 'on_leave'].includes(technician.availability.status)).map((technician) => <option key={technician.id} value={technician.id}>{technician.name}</option>)}</select></label><label>Visit title<input name="title" required maxLength={160} /></label><label>Visit priority<select name="priority" defaultValue="normal">{['low', 'normal', 'high', 'critical'].map((priority) => <option key={priority}>{priority}</option>)}</select></label><label>Visit starts<input name="startsAt" type="datetime-local" required /></label><label>Visit ends<input name="endsAt" type="datetime-local" required /></label><label className="wide">Visit description<textarea name="description" maxLength={2000} /></label><button disabled={busy || !eligible.length}>Schedule visit</button></form></section>}
    <section className="panel"><h2>Technician availability and qualifications</h2>{matrix?.technicians.map((technician) => <article className="evidence" key={technician.id}><strong>{technician.name}</strong><p>{technician.jobTitle} · {technician.availability.status} · {technician.availability.dailyCapacityHours} hours/day · {technician.availability.workingDays.join(', ')}</p><p>Skills: {technician.skills.map((skill) => skill.code).join(', ') || 'None'}</p>{technician.certificates.map((certificate, index) => <small className="certificate" key={index}>{certificate.type} · {certificate.issuer} · expires {new Date(certificate.validUntil).toLocaleDateString()}{Date.parse(certificate.validUntil) < Date.now() && ' (expired)'}</small>)}{matrix.permissions.manage && <label>Availability for {technician.name}<select disabled={busy} value={technician.availability.status} onChange={(e) => void save(() => api.updateAvailability(technician.id, { ...technician.availability, status: e.target.value }))}>{['available', 'busy', 'off_duty', 'on_leave'].map((status) => <option key={status}>{status}</option>)}</select></label>}</article>)}</section>
    {matrix?.permissions.manage && <section className="panel"><h2>Add technician qualification</h2><form className="schedule-form" onSubmit={qualification}><label>Qualification technician<select required value={technicianId} onChange={(e) => setTechnicianId(e.target.value)}><option value="">Select technician</option>{matrix.technicians.map((technician) => <option key={technician.id} value={technician.id}>{technician.name}</option>)}</select></label><label>Qualification kind<select name="kind"><option value="skill">Skill</option><option value="certificate">Certificate</option></select></label><label>Qualification code<input name="code" required pattern="[a-z0-9][a-z0-9._-]{1,119}" /></label><label>Certificate issuer<input name="issuer" maxLength={160} /></label><label>Certificate expiry<input name="validUntil" type="date" /></label><button disabled={busy}>Save qualification</button></form></section>}
  </div>;
}
