CREATE TABLE application_snapshots (id smallint PRIMARY KEY CHECK (id=1),payload jsonb NOT NULL,saved_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (user_token text PRIMARY KEY,id text NOT NULL,email text NOT NULL,tenant_id text NOT NULL,role text NOT NULL,data jsonb NOT NULL);
CREATE UNIQUE INDEX users_email_lower_idx ON users(lower(email)); CREATE INDEX users_tenant_idx ON users(tenant_id);
CREATE TABLE authenticated_sessions (token_hash text PRIMARY KEY,user_token text NOT NULL,expires_at timestamptz NOT NULL,data jsonb NOT NULL);
CREATE INDEX authenticated_sessions_expiry_idx ON authenticated_sessions(expires_at);
CREATE TABLE robots (id text PRIMARY KEY,tenant_id text NOT NULL,serial_number text NOT NULL,model_id text NOT NULL,status text NOT NULL,data jsonb NOT NULL,updated_at timestamptz NOT NULL);
CREATE UNIQUE INDEX robots_tenant_serial_idx ON robots(tenant_id,lower(serial_number)); CREATE INDEX robots_tenant_status_idx ON robots(tenant_id,status);
CREATE TABLE passport_entries (id text PRIMARY KEY,robot_id text NOT NULL,tenant_id text,entry_type text NOT NULL,occurred_at timestamptz NOT NULL,data jsonb NOT NULL);
CREATE INDEX passport_entries_robot_time_idx ON passport_entries(robot_id,occurred_at DESC);
CREATE TABLE events (id text PRIMARY KEY,tenant_id text NOT NULL,robot_id text NOT NULL,event_type text NOT NULL,severity text NOT NULL,occurred_at timestamptz NOT NULL,data jsonb NOT NULL);
CREATE INDEX events_tenant_time_idx ON events(tenant_id,occurred_at DESC); CREATE INDEX events_robot_time_idx ON events(robot_id,occurred_at DESC);
CREATE TABLE audit_entries (id text PRIMARY KEY,tenant_id text,actor_id text,action text NOT NULL,object_type text,object_id text,occurred_at timestamptz NOT NULL,data jsonb NOT NULL);
CREATE INDEX audit_tenant_time_idx ON audit_entries(tenant_id,occurred_at DESC);
CREATE TABLE provider_tasks (provider text NOT NULL,task_id text NOT NULL,robot_external_id text,data jsonb NOT NULL,PRIMARY KEY(provider,task_id));
CREATE INDEX provider_tasks_robot_idx ON provider_tasks(provider,robot_external_id);
CREATE TABLE attachments (id uuid PRIMARY KEY,tenant_id text NOT NULL,robot_id text NOT NULL,object_key text NOT NULL UNIQUE,filename text NOT NULL,content_type text NOT NULL,size_bytes integer NOT NULL,sha256 text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX attachments_robot_idx ON attachments(robot_id,created_at DESC);
CREATE TABLE sync_jobs (id uuid PRIMARY KEY,provider text NOT NULL CHECK(provider IN ('autoxing','cenobots')),tenant_id text NOT NULL,actor jsonb NOT NULL,trigger text NOT NULL DEFAULT 'manual',status text NOT NULL CHECK(status IN ('queued','running','succeeded','failed')),attempts integer NOT NULL DEFAULT 0,worker_id text,locked_at timestamptz,result jsonb,error text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),started_at timestamptz,completed_at timestamptz);
CREATE UNIQUE INDEX sync_jobs_one_active_provider_idx ON sync_jobs(tenant_id,provider) WHERE status IN ('queued','running'); CREATE INDEX sync_jobs_claim_idx ON sync_jobs(status,created_at); CREATE INDEX sync_jobs_tenant_time_idx ON sync_jobs(tenant_id,created_at DESC);
