'use client';

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Locale = 'de' | 'en';

const de: Record<string, string> = {
  'Financial operations':'Finanzbetrieb','Cost tracking':'Kostenverfolgung','Gross costs':'Bruttokosten','active entries':'aktive Einträge','Net costs':'Nettokosten','Before tax':'Vor Steuern','Tax':'Steuer','voided entries':'stornierte Einträge','Record cost':'Kosten erfassen','Robot':'Roboter','Quantity':'Menge','Unit cost (EUR)':'Stückkosten (EUR)','VAT':'MwSt.','Vendor':'Lieferant','Reference':'Referenz','Cost entries':'Kosteneinträge','Net':'Netto','Gross':'Brutto','Status':'Status','Actions':'Aktionen','Void':'Stornieren','No costs recorded for this period.':'Für diesen Zeitraum wurden keine Kosten erfasst.','Cost entry recorded.':'Kosteneintrag erfasst.','Cost entry voided.':'Kosteneintrag storniert.','Reason for voiding this cost entry':'Grund für die Stornierung dieses Kosteneintrags',
  'Overview':'Übersicht','Events & service':'Ereignisse & Service','Support':'Support','Technicians':'Techniker','Reports':'Berichte','Audit log':'Prüfprotokoll','Integrations':'Integrationen','Administration':'Verwaltung','Updated':'Aktualisiert','days':'Tage','Active':'Aktiv','Paused':'Pausiert','sent':'gesendet','failed':'fehlgeschlagen','daily':'täglich','weekly':'wöchentlich','monthly':'monatlich','Automated delivery':'Automatischer Versand','Report schedules could not be loaded':'Berichtszeitpläne konnten nicht geladen werden.','Report schedule created.':'Berichtszeitplan erstellt.','Report sent.':'Bericht gesendet.','Schedule paused.':'Zeitplan pausiert.','Schedule resumed.':'Zeitplan fortgesetzt.','Schedule deleted.':'Zeitplan gelöscht.','Delete this report schedule?':'Diesen Berichtszeitplan löschen?','Sunday':'Sonntag','Monday':'Montag','Tuesday':'Dienstag','Wednesday':'Mittwoch','Thursday':'Donnerstag','Friday':'Freitag','Saturday':'Samstag','View daily data':'Tagesdaten anzeigen','Daily event trend':'Täglicher Ereignisverlauf','Date':'Datum','Errors':'Fehler','Maintenance':'Wartung','Tasks':'Aufgaben',
  'Secure platform access':'Sicherer Plattformzugang','Sign in to Altegro':'Bei Altegro anmelden','Open the workspace for your organization, role and assigned robots.':'Öffnen Sie den Arbeitsbereich für Ihre Organisation, Rolle und zugewiesenen Roboter.','Email':'E-Mail','Password':'Passwort','Signing in…':'Anmeldung…','Sign in':'Anmelden','Manufacturer-neutral operations':'Herstellerneutraler Betrieb','One clear workspace for every role.':'Ein übersichtlicher Arbeitsbereich für jede Rolle.','Registry, Passport, service evidence and integrations without exposing tools a user does not need.':'Register, Roboterpass, Servicenachweise und Integrationen – ohne unnötige Werkzeuge.','Loading Altegro…':'Altegro wird geladen…','robot operations':'Roboterbetrieb','Phase 1 · Read-first':'Phase 1 · Lesemodus','Alerts':'Warnungen','Refreshing…':'Aktualisierung…','Refresh':'Aktualisieren','Log out':'Abmelden','Role workspace':'Rollen-Arbeitsbereich','Retry':'Erneut versuchen','Fleet priorities at a glance':'Flottenprioritäten auf einen Blick','Data and actions are limited to your tenant, role and robot assignments.':'Daten und Aktionen sind auf Ihren Mandanten, Ihre Rolle und Ihre Roboterzuweisungen begrenzt.','Waiting for data':'Warten auf Daten','Robots':'Roboter','online':'online','Needs attention':'Handlungsbedarf','Offline robots and active errors':'Offline-Roboter und aktive Fehler','Open service':'Offener Service','closed':'geschlossen','Passport coverage':'Pass-Abdeckung','certificates due':'Zertifikate fällig','Recent fleet':'Aktuelle Flotte','View registry':'Register öffnen','Integration health':'Integrationsstatus','Providers':'Anbieter','Open integrations':'Integrationen öffnen','Integration plane':'Integrationsebene','Provider contracts':'Anbieterverträge','Commands disabled by default':'Befehle standardmäßig deaktiviert','Migration workspace':'Migrationsbereich','The complete administration page remains available in the existing portal.':'Die vollständige Verwaltungsseite bleibt im bestehenden Portal verfügbar.','No robots are visible in this workspace.':'In diesem Arbeitsbereich sind keine Roboter sichtbar.','No telemetry':'Keine Telemetrie','Integration details are unavailable for this role.':'Integrationsdetails sind für diese Rolle nicht verfügbar.','No read capabilities':'Keine Lesefunktionen','never':'nie','guarded commands':'geschützte Befehle','read only':'nur lesen',
  'Decision metrics':'Entscheidungskennzahlen','Advanced analytics':'Erweiterte Analysen','Period':'Zeitraum','7 days':'7 Tage','30 days':'30 Tage','90 days':'90 Tage','365 days':'365 Tage','Fleet health':'Flottenzustand','need attention':'benötigen Aufmerksamkeit','Availability':'Verfügbarkeit','Task success':'Aufgabenerfolg','completed':'abgeschlossen','High maintenance risk':'Hohes Wartungsrisiko','Service performance':'Serviceleistung','Closure rate':'Abschlussquote','Average resolution':'Durchschnittliche Lösung','Overdue maintenance':'Überfällige Wartung','Incidents per robot':'Vorfälle je Roboter','Provider distribution':'Anbieterverteilung','Workforce capacity':'Personalkapazität','Available':'Verfügbar','On leave':'Abwesend','Total technicians':'Techniker gesamt','Export CSV':'CSV exportieren','Export JSON':'JSON exportieren','Predictive maintenance':'Vorausschauende Wartung','Highest-risk robots':'Roboter mit höchstem Risiko','need review':'müssen geprüft werden','No current warning factors.':'Keine aktuellen Warnfaktoren.','No robot data is available for predictions.':'Keine Roboterdaten für Prognosen verfügbar.','Loading operational analytics…':'Betriebsanalysen werden geladen…',
  'Active failures':'Aktive Störungen','Error and critical alerts':'Fehler und kritische Warnungen','Unread alerts':'Ungelesene Warnungen','Personal read status':'Persönlicher Lesestatus','Overdue service':'Überfälliger Service','Scheduled maintenance':'Geplante Wartung','Active schedules':'Aktive Zeitpläne','Recurring maintenance plans':'Wiederkehrende Wartungspläne','Automatic monitoring · 30-second refresh':'Automatische Überwachung · Aktualisierung alle 30 Sekunden','Failure alerts':'Störungswarnungen','Mark all read':'Alle als gelesen markieren','Search':'Suchen','Robot, failure or source':'Roboter, Störung oder Quelle','Severity':'Schweregrad','All severities':'Alle Schweregrade','Critical':'Kritisch','Error':'Fehler','Warning':'Warnung','Information':'Information','Acknowledge':'Bestätigen','Resolve':'Lösen','No alerts match these filters.':'Keine Warnungen entsprechen diesen Filtern.','Preventive service':'Vorbeugender Service','schedules':'Zeitpläne','Maintenance robot':'Wartungsroboter','Select robot':'Roboter auswählen','Service title':'Servicetitel','Quarterly inspection':'Vierteljährliche Inspektion','Next due':'Nächste Fälligkeit','Repeat every (days)':'Wiederholen alle (Tage)','Reminder (days)':'Erinnerung (Tage)','Priority':'Priorität','Low':'Niedrig','Normal':'Normal','High':'Hoch','Description':'Beschreibung','Inspection scope and safety notes':'Prüfumfang und Sicherheitshinweise','Saving…':'Speichern…','Create schedule':'Zeitplan erstellen','No visible robot is available for scheduling.':'Kein sichtbarer Roboter ist für die Planung verfügbar.','Complete':'Abschließen','Pause':'Pausieren','Resume':'Fortsetzen','No recurring maintenance has been scheduled.':'Keine wiederkehrende Wartung geplant.','Loading alerts and maintenance…':'Warnungen und Wartung werden geladen…',
  'Immutable operational evidence':'Unveränderliche Betriebsnachweise','Detailed audit log':'Detailliertes Prüfprotokoll','Action, actor, object or detail':'Aktion, Person, Objekt oder Detail','Action':'Aktion','All actions':'Alle Aktionen','Result':'Ergebnis','All results':'Alle Ergebnisse','Actor':'Person','All actors':'Alle Personen','Object':'Objekt','All objects':'Alle Objekte','From':'Von','To':'Bis','Loading…':'Laden…','Apply filters':'Filter anwenden','View recorded details':'Erfasste Details anzeigen','No audit records match these filters.':'Keine Prüfprotokolle entsprechen diesen Filtern.',
  'Robot registry':'Roboterregister','Search robots':'Roboter suchen','Serial number, model or site':'Seriennummer, Modell oder Standort','No robots are visible.':'Keine Roboter sichtbar.','Loading Passport…':'Roboterpass wird geladen…','Owner:':'Eigentümer:','Operator:':'Betreiber:','Unassigned':'Nicht zugewiesen','Identity and configuration':'Identität und Konfiguration','Maintenance PDF':'Wartungs-PDF','Compliance PDF':'Compliance-PDF','Export Passport':'Roboterpass exportieren','Documents':'Dokumente','Add Passport document':'Passdokument hinzufügen','Document title':'Dokumenttitel','Attachment (maximum 2 MB)':'Anhang (maximal 2 MB)','Document description':'Dokumentbeschreibung','Save document':'Dokument speichern','Certificates':'Zertifikate','Deployments':'Bereitstellungen','Service history':'Serviceverlauf','No service cases recorded.':'Keine Servicefälle erfasst.','Qualifications and compatibility':'Qualifikationen und Kompatibilität','Required qualifications':'Erforderliche Qualifikationen','Qualified':'Qualifiziert','Qualification missing':'Qualifikation fehlt','Complete lifecycle timeline':'Vollständiger Lebenszyklus',
  'Create support ticket':'Support-Ticket erstellen','Support robot':'Support-Roboter','Ticket title':'Ticket-Titel','Category':'Kategorie','Ticket priority':'Ticket-Priorität','Issue description':'Problembeschreibung','Ticket attachment (maximum 2 MB)':'Ticket-Anhang (maximal 2 MB)','Create ticket':'Ticket erstellen','Support tickets':'Support-Tickets','Search tickets':'Tickets durchsuchen','Filter ticket status':'Ticketstatus filtern','All statuses':'Alle Status','Loading tickets…':'Tickets werden geladen…','No tickets yet.':'Noch keine Tickets.','Reply message':'Antwort','Reply status':'Antwortstatus','Reply attachment (maximum 2 MB)':'Antwortanhang (maximal 2 MB)','Send reply':'Antwort senden',
  'Technician calendar':'Technikerkalender','Week starting':'Wochenbeginn','Times use your browser’s local timezone. Qualifications and overlapping bookings are checked before saving.':'Zeiten verwenden die lokale Zeitzone Ihres Browsers. Qualifikationen und Überschneidungen werden vor dem Speichern geprüft.','Work status':'Arbeitsstatus','Completion note':'Abschlussnotiz','Update work order':'Arbeitsauftrag aktualisieren','Loading workforce…':'Personal wird geladen…','Schedule technician visit':'Technikerbesuch planen','Visit robot':'Roboter','Qualified technician':'Qualifizierter Techniker','Select qualified technician':'Qualifizierten Techniker auswählen','Visit title':'Besuchstitel','Visit priority':'Priorität','Visit starts':'Beginn','Visit ends':'Ende','Visit description':'Beschreibung','Schedule visit':'Besuch planen','Technician availability and qualifications':'Technikerverfügbarkeit und Qualifikationen','Skills:':'Kenntnisse:','None':'Keine','Add technician qualification':'Technikerqualifikation hinzufügen','Qualification technician':'Techniker','Select technician':'Techniker auswählen','Qualification kind':'Qualifikationsart','Skill':'Kenntnis','Certificate':'Zertifikat','Qualification code':'Qualifikationscode','Certificate issuer':'Zertifikatsaussteller','Certificate expiry':'Zertifikatsablauf','Save qualification':'Qualifikation speichern',
  'Fleet comparison':'Flottenvergleich','Compare by':'Vergleichen nach','Site':'Standort','Provider':'Anbieter','Comparison period':'Vergleichszeitraum','Loading comparison…':'Vergleich wird geladen…','Current / previous totals and absolute change':'Aktuell / vorher und absolute Änderung','Robots / online now':'Roboter / jetzt online','Events':'Ereignisse','Incidents':'Vorfälle','Cases opened':'Fälle eröffnet','Cases closed':'Fälle geschlossen','Maintenance completed':'Wartungen abgeschlossen','No visible fleet to compare.':'Keine sichtbare Flotte zum Vergleichen.',
  'Scheduled email reports':'Geplante E-Mail-Berichte','Create report schedule':'Berichtszeitplan erstellen','Report name':'Berichtsname','Operations summary':'Betriebsübersicht','Frequency':'Häufigkeit','Daily':'Täglich','Weekly':'Wöchentlich','Monthly':'Monatlich','Report period':'Berichtszeitraum','Delivery hour (UTC)':'Versandstunde (UTC)','Weekday':'Wochentag','Day of month':'Tag im Monat','Create report':'Bericht erstellen','Delivery email':'Versandadresse','Next delivery':'Nächster Versand','Last delivery':'Letzter Versand','Send now':'Jetzt senden','Delete':'Löschen','No report schedules yet.':'Noch keine Berichtszeitpläne.','Email delivery is not configured. An administrator must configure SMTP before reports can be sent.':'Der E-Mail-Versand ist nicht konfiguriert. Ein Administrator muss SMTP einrichten, bevor Berichte gesendet werden können.','English':'Englisch','German':'Deutsch','Language':'Sprache','Skip to main content':'Zum Hauptinhalt springen'
};

type I18nValue = { locale: Locale; setLocale: (locale: Locale) => void; t: (text: string) => string; formatDate: (value: string | Date) => string; formatDateTime: (value: string | Date) => string };
const I18nContext=createContext<I18nValue | null>(null);

const originalText=new Map<Text,string>();
function translateTextNode(node: Text, locale: Locale) {
  const raw=node.nodeValue || ''; const trimmed=raw.trim(); if (!trimmed) return; let original=originalText.get(node) || trimmed; const previousTranslation=de[original] || original; if (trimmed !== original && trimmed !== previousTranslation) original=trimmed; originalText.set(node,original); const translated=locale === 'de' ? de[original] || original : original; if (translated !== trimmed) node.nodeValue=raw.replace(trimmed,translated);
}

function localizeTree(root: ParentNode,locale: Locale) {
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT); let current: Node | null; while ((current=walker.nextNode())) { const parent=current.parentElement; if (!parent || ['SCRIPT','STYLE','CODE','PRE'].includes(parent.tagName) || parent.closest('[data-no-translate]')) continue; translateTextNode(current as Text,locale); }
  root.querySelectorAll?.<HTMLElement>('[placeholder],[title],[aria-label]').forEach((element) => { for (const attribute of ['placeholder','title','aria-label']) { const value=element.getAttribute(attribute); if (!value) continue; const key=`i18n${attribute.replaceAll('-','')}`; const original=element.dataset[key] || value; element.dataset[key]=original; element.setAttribute(attribute,locale === 'de' ? de[original] || original : original); } });
}

export function I18nProvider({ children }: { children: ReactNode }) {
  const [locale,setLocaleState]=useState<Locale>('en');
  useEffect(() => { const saved=window.localStorage.getItem('altegro-locale'); if (saved === 'en' || saved === 'de') setLocaleState(saved); },[]);
  useEffect(() => { document.documentElement.lang=locale; window.localStorage.setItem('altegro-locale',locale); if (locale === 'en') { for (const [node,original] of originalText) { if (!node.isConnected) { originalText.delete(node); continue; } const raw=node.nodeValue || ''; const trimmed=raw.trim(); if (trimmed && trimmed !== original) node.nodeValue=raw.replace(trimmed,original); } return; } let applying=false; const apply=(root: ParentNode=document.body) => { if (applying) return; applying=true; localizeTree(root,locale); applying=false; }; apply(); const observer=new MutationObserver((mutations) => { if (applying) return; for (const mutation of mutations) { if (mutation.type === 'characterData' && mutation.target.parentNode) apply(mutation.target.parentNode as ParentNode); for (const node of mutation.addedNodes) if (node.nodeType === Node.ELEMENT_NODE) apply(node as ParentNode); } }); observer.observe(document.body,{ childList:true,subtree:true,characterData:true }); return () => observer.disconnect(); },[locale]);
  const value=useMemo<I18nValue>(() => ({ locale,setLocale:(next) => setLocaleState(next),t:(text) => locale === 'de' ? de[text] || text : text,formatDate:(input) => new Date(input).toLocaleDateString(locale === 'de' ? 'de-DE' : 'en-GB'),formatDateTime:(input) => new Date(input).toLocaleString(locale === 'de' ? 'de-DE' : 'en-GB') }),[locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() { const value=useContext(I18nContext); if (!value) throw new Error('useI18n must be used within I18nProvider'); return value; }
